Connected Django in project
euggeze/project_web pull request #4
Opened 2021-07-14 09:50 UTC by euggeze

Created directories, created setup.py, download Django and used command 'startproject'

2021-07-15 06:55 UTC, inauros requested changes
1. Django application must be set up using the startproject and startapp commands and then the required packages described above must be created manually.
2. .pyc files should be added to .gitignore
3. python packages must include __init__.py instead of .gitkeep (ONLY python packages, not python packages, must include .gitkeep)

2021-07-16 09:22 UTC, inauros requested changes

2021-07-16 09:22 UTC, inauros commented on department_project/department_app/models.py
> +# Create your models here.
Please remove this module.

2021-07-16 09:22 UTC, inauros commented on department_project/department_app/tests.py
> +# Create your tests here.
Please remove this module.

2021-07-16 09:22 UTC, inauros commented on department_project/department_app/views.py
> +# Create your views here.
Please remove this module.

2021-07-16 09:31 UTC, euggeze commented on department_project/department_app/models.py
> +# Create your models here.
Done

2021-07-16 09:31 UTC, euggeze commented on department_project/department_app/tests.py
> +# Create your tests here.
Done

2021-07-16 09:31 UTC, euggeze commented on department_project/department_app/views.py
> +# Create your views here.
Done

2021-07-16 09:37 UTC, inauros approved these changes

2021-07-16 09:39 UTC, merged