Configure CI/CD
euggeze/project_web pull request #5
Opened 2021-07-20 10:40 UTC by euggeze

Created a build configuration. Added coveralls and pylint to the configuration. Added badges to readme file.

2021-07-21 07:07 UTC, inauros requested changes
Please fix the following errors generated by pylint:
************* Module department_app.tests.placeholder_test
department_project/department_app/tests/placeholder_test.py:2:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation) 
department_project/department_app/tests/placeholder_test.py:1:0: C0114: Missing module docstring (missing-module-docstring) 
department_project/department_app/tests/placeholder_test.py:1:0: C0116: Missing function or method docstring (missing-function-docstring) 
**Fixed**

2021-07-21 07:07 UTC, inauros commented on .coveragerc
> +	*apps.py
Please could you explain, why you ignored these files?

2021-07-21 07:07 UTC, inauros commented on .github/workflows/python_package.yml
> +on: [push]
Please include pull requests as well.

2021-07-21 07:07 UTC, inauros commented on .github/workflows/python_package.yml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Please remove the "if" statement. The build should fail if the requirements.txt file does not exist.

2021-07-21 07:07 UTC, inauros commented on .gitignore
> +.coveralls.yml
Why this file was added to .gitignore?

2021-07-21 07:07 UTC, inauros commented on .pylintrc
> +        comprehension-escape
Please clear this list. Errors that should really be ignored will be added at development time step by step.

2021-07-21 07:07 UTC, inauros commented on .pylintrc
> +max-line-length=100
please replace 100 with 120 - we use exactly this line length

2021-07-22 09:07 UTC, euggeze commented on .coveragerc
> +	*apps.py
These files are not included in the program.

2021-07-22 09:07 UTC, euggeze commented on .github/workflows/python_package.yml
> +on: [push]
Done

2021-07-22 09:07 UTC, euggeze commented on .github/workflows/python_package.yml
> +          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Fixed

2021-07-22 09:08 UTC, euggeze commented on .gitignore
> +.coveralls.yml
There is a token in this file, which must not be public.

2021-07-22 09:08 UTC, euggeze commented on .pylintrc
> +        comprehension-escape
Done

2021-07-22 09:09 UTC, euggeze commented on .pylintrc
> +max-line-length=100
Done

2021-07-23 09:51 UTC, inauros approved these changes

2021-07-23 09:52 UTC, merged